### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Juke34** [djhn75/RNAEditor#28]
Any reason to use picard<=1.119
Do more recent versions do the job?
What about GATK did you try more recent versions?

I would be happy to make some tests if you provide any data test and tests with the tool.

**Comment by rsdmse** [comment]
@djhn75 I appreciate the recent upgrade to Qt5. I have a similar question regarding GATK. Is RNAEditor only compatible with version 3.5? I found the corresponding [commit](https://github.com/broadgsa/gatk/tree/00fbcb36b2b2eba8a5c4ab32d26fa89c9637b04a) for the GATK repo, but it's not obvious how to install it. Would you mind sharing your experience?

If a more recent GATK version (especially 4+) can be used that would be great.

**Comment by djhn75** [comment]
Currently RNAEditor only works with GATK 3.5, which you can download here (https://console.cloud.google.com/storage/browser/gatk-software/package-archive/gatk;tab=objects?prefix=&forceOnObjectsSortingFiltering=false).

I am working on another update where i integrate the newer version of GATK and PiccardTools, but there are major differences also in SNP Calling (See here: https://gatk.broadinstitute.org/hc/en-us/community/posts/6035032472347-Differences-between-GATK-3-5-and-4-2-5). So i need to test a little bit further till i can publish this version.

Thanks for your patients

Best

**Comment by rsdmse** [comment]
Thank you. I was able to containerize it and get to the start menu. However, when I click on the GTF file the window crashes with `AttributeError: module 'PyQt5.QtGui' has no attribute 'QWidget'`. This is likely to be caused by mixing Qt4/5.

**Comment by rsdmse** [comment]
Version 1.0 with Qt4 seems to work, but our user reports that upon starting the analysis with a .bam file, a pop-up error is shown:
`module 'PyQt4.QtCore' has no attribute 'QString'Cannot start Analysis!`

**Comment by rsdmse** [comment]
I appreciate your updates to the repo. Menu buttons in version 1.1a with Qt5 now work, but when I start an analysis it shows an error that it can't find Java, but I've checked that the condition is true:

```
python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.system("java -version") == 0
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
True
```

There are three files that contain the `"Java could not be found, Please install java"` error message: `CallEditingSites.py`, `MapFastq.py`, `RNAEDitor.py`. (We are running the third one.) They all check for java in this manner:
```
if not os.system("java -version")==0:
```

I am puzzled by this behavior. Do you have any suggestions about this error?
